import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sam Tian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
      <main>
        
      </main>
    </div>
  )
}
